Update cicd.yaml

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -60,12 +60,18 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      # ✅ Argo CD CLI 설치
-      - name: Install Argo CD CLI
+      # ✅ Argo CD CLI 설치 (설치되어 있지 않은 경우)
+      - name: Install Argo CD CLI (if not installed)
         run: |
-          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
-          chmod +x argocd-linux-amd64
-          sudo mv argocd-linux-amd64 /usr/local/bin/argocd
+           if ! command -v argocd &> /dev/null
+           then
+             echo "Argo CD CLI not found, installing..."
+             curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+             chmod +x argocd-linux-amd64
+             sudo mv argocd-linux-amd64 /usr/local/bin/argocd
+            else
+             echo "Argo CD CLI already installed."
+            fi
 
       # ✅ Argo CD 로그인
       - name: Login to Argo CD
